# Generated by Django 4.2.6 on 2023-10-31 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='codigo',
        ),
    ]
