# Generated by Django 4.2.6 on 2023-10-31 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_disciplina_options_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='codigo',
        ),
    ]
