# Generated by Django 4.2.6 on 2023-10-31 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_aluno_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.AddField(
            model_name='turma',
            name='nome',
            field=models.CharField(default='Sem Nome', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default='Sem Nome', max_length=50),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='usuario',
            field=models.OneToOneField(limit_choices_to={'papel': 'Professor'}, on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='alunos_matriculados',
            field=models.ManyToManyField(to='app.usuario'),
        ),
    ]
