# Generated by Django 4.2.6 on 2023-11-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_usuario_user_turma_nome_usuario_nome_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['aluno'], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['professor'], 'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='usuario',
            new_name='aluno',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='usuario',
            new_name='professor',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='turmas',
        ),
        migrations.AddField(
            model_name='aluno',
            name='disciplinas_cursadas',
            field=models.ManyToManyField(to='app.disciplina'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia_da_semana',
            field=models.CharField(choices=[('Segunda', 'Segunda-feira'), ('Terca', 'Terça-feira'), ('Quarta', 'Quarta-feira'), ('Quinta', 'Quinta-feira'), ('Sexta', 'Sexta-feira')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='papel',
            field=models.CharField(choices=[('Aluno', 'Aluno'), ('Professor', 'Professor')], max_length=15),
        ),
        migrations.DeleteModel(
            name='Turma',
        ),
    ]
