# Generated by Django 4.2.6 on 2023-11-27 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_aluno_options_alter_professor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='hora_de_termino',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='aluno',
            field=models.OneToOneField(limit_choices_to={'papel': 'Aluno'}, on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia_da_semana',
            field=models.CharField(choices=[('Segunda', 'Segunda-feira'), ('Terca', 'Terça-feira'), ('Quarta', 'Quarta-feira'), ('Quinta', 'Quinta-feira'), ('Sexta', 'Sexta-feira'), ('Sabado', 'Sábado')], max_length=20),
        ),
    ]
