# Generated by Django 4.2.6 on 2023-12-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_horario_hora_de_termino_alter_aluno_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='hora_de_inicio',
            field=models.CharField(choices=[(1, '13:00'), (2, '13:55'), (3, '15:10'), (4, '16:05'), (5, '19:00'), (6, '19:55'), (7, '21:10'), (8, '22:05')]),
        ),
    ]
